version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - _output
  skip-files:
    - ".*\\.test$"
    - "zz_generated\\..*\\.go$"
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - errcheck

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
  staticcheck:
    go: "1.25"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: zz_generated\.deepcopy\.go
      linters:
        - govet
    - path: zz_generated\.managed\.go
      linters:
        - govet
    - path: zz_generated\.managedlist\.go
      linters:
        - govet
  exclude-use-default: false
