apiVersion: smtpcredential.mailgun.m.crossplane.io/v1beta1
kind: SMTPCredential
metadata:
  namespace: default
  name: vaultwarden-smtp
spec:
  forProvider:
    domain: example.com
    login: mail@example.com
  providerConfigRef:
    name: mailgun-config
  writeConnectionSecretsToRef:
    name: vaultwarden-smtp-credentials
    namespace: vaultwarden
