apiVersion: smtpcredential.mailgun.m.crossplane.io/v1beta1
kind: SMTPCredential
metadata:
  namespace: default
  name: example-smtp-credential
spec:
  forProvider:
    domain: example.com
    login: mail@example.com
  providerConfigRef:
    name: mailgun-config
  writeConnectionSecretToRef:
    name: example-smtp-credentials
