//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

func (in *MailingList) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return in.Status.GetCondition(ct)
}

func (in *MailingList) SetConditions(c ...xpv2.Condition) {
	in.Status.SetConditions(c...)
}

func (in *MailingList) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return in.Spec.ProviderConfigReference
}

func (in *MailingList) GetManagementPolicies() xpv2.ManagementPolicies {
	return in.Spec.ManagementPolicies
}

func (in *MailingList) SetManagementPolicies(p xpv2.ManagementPolicies) {
	in.Spec.ManagementPolicies = p
}

func (in *MailingList) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return in.Spec.WriteConnectionSecretToReference
}

func (in *MailingList) ConnectionSecretName() string {
	ref := in.GetWriteConnectionSecretToReference()
	if ref == nil {
		return ""
	}
	return ref.Name
}
