{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "provider-mailgun.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider-mailgun.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "provider-mailgun.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Allow metrics scraping
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.port }}

  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Allow HTTPS to Mailgun API
    - to: []
      ports:
        - protocol: TCP
          port: 443

    # Allow HTTP for health checks
    - to: []
      ports:
        - protocol: TCP
          port: 80

    # Allow Kubernetes API access
    - to: []
      ports:
        - protocol: TCP
          port: 6443

    {{- if .Values.networkPolicy.egress }}
    # Additional egress rules
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
    {{- end }}
{{- end }}
